### ISSUE TITLE
Remove MockMvc from project and replace with WebTestClient

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/salary-calc#9]
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/web/reactive/server/WebTestClient.html
https://www.baeldung.com/spring-5-webclient

**Comment by rohanshankar** [comment]
I can take a look at it if it is still an issue that is available

**Comment by mfvanek** [comment]
@rohanshankar
 Yes, it 's still relevant. I've assigned it to you. Feel free to contribute

**Comment by mfvanek** [comment]
@rohanshankar 
Any update on it?
